//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive
    {
        public int ID { get; set; }
        public int IDParking { get; set; }
    
        public virtual Parking Parking { get; set; }
    }
}
